"""Tests for the database interface contract between this repo and the data/ML repo."""
import sqlite3
from pathlib import Path

import numpy as np
import pytest

from nugrade.db_contract import (
    EMBEDDING_DIM,
    EMBEDDING_DTYPE,
    REQUIRED_SCHEMA,
    SchemaError,
    verify_schema,
)

BASE_DIR = Path(__file__).parent.parent
DB_PATH = BASE_DIR / "data" / "nugrade_data.db"

requires_db = pytest.mark.skipif(
    not DB_PATH.is_file(), reason="nugrade_data.db is generated by the data/ML repo"
)


@requires_db
def test_real_database_satisfies_the_contract():
    """The shipped database must contain everything this app reads."""
    con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    try:
        verify_schema(con)
    finally:
        con.close()


def test_missing_column_is_rejected():
    """A database missing a column this app reads must fail loudly, not silently."""
    con = sqlite3.connect(":memory:")
    con.execute("CREATE TABLE measurements (Z INT)")  # missing nearly everything
    con.execute("CREATE TABLE subentries (Z INT)")
    con.execute("CREATE TABLE sentence_embeddings (EXFOR_Entry TEXT)")

    with pytest.raises(SchemaError) as excinfo:
        verify_schema(con, check_embeddings=False)
    assert "missing column" in str(excinfo.value)
    con.close()


def test_wrong_embedding_dimensionality_is_rejected():
    """An embedding of the wrong size means the two repos disagree about the model."""
    con = sqlite3.connect(":memory:")
    for table, columns in REQUIRED_SCHEMA.items():
        cols = ", ".join(f'"{c}"' for c in sorted(columns))
        con.execute(f"CREATE TABLE {table} ({cols})")
    con.execute(
        "INSERT INTO sentence_embeddings (Embedding) VALUES (?)",
        (np.zeros(128, dtype=EMBEDDING_DTYPE).tobytes(),),
    )

    with pytest.raises(SchemaError, match="dimensional"):
        verify_schema(con)
    con.close()


# --- Query/document embedding-space agreement --------------------------------
#
# Stored sentence embeddings are attention-mask-weighted mean-pooled SciBERT,
# generated by get_embeddings_batch in NuGrade-PreProcessing/2_report_embedding.ipynb.
# NuclearDataAgent._embed must use the identical pooling, or query and document
# vectors live in different spaces and similarity ranking silently degrades.
# (_embed originally used the CLS token; fixed after confirming the notebook.)

@requires_db
def test_query_embedding_matches_stored_pooling():
    """A query embedding must live in the same space as the stored document vectors."""
    pytest.importorskip("transformers", reason="SciBERT not installed")
    from nugrade.ai_agent import NuclearDataAgent

    con = sqlite3.connect(f"file:{DB_PATH}?mode=ro", uri=True)
    text, blob = con.execute(
        "SELECT Text, Embedding FROM sentence_embeddings "
        "WHERE Embedding IS NOT NULL AND length(Text) > 80 LIMIT 1"
    ).fetchone()
    con.close()

    stored = np.frombuffer(blob, dtype=EMBEDDING_DTYPE)  # read-only view
    stored = stored / np.linalg.norm(stored)

    agent = NuclearDataAgent.__new__(NuclearDataAgent)  # skip API-key setup
    assert agent._load_scibert()
    requery = agent._embed(text)

    assert requery.shape == (EMBEDDING_DIM,)
    # Re-embedding a sentence must reproduce its own stored vector.
    assert float(np.dot(requery, stored)) == pytest.approx(1.0, abs=1e-3)
