"""Schema contract for the SQLite database produced by the data/ML repo.

The database is the interface between two repos: the data/ML notebooks generate it,
and this Flask app consumes it read-only. Nothing in this repo can fix a bad database,
so the only useful behaviour on a mismatch is to fail loudly at startup rather than
serve wrong answers.

Only the tables this app actually reads are covered. `reports`, `report_embeddings`,
and `entries` are consumed by the KNN pipeline in the data/ML repo and are
deliberately not constrained here.
"""
import numpy as np

# Columns this app depends on, per table. Extra columns are fine; missing ones are not.
REQUIRED_SCHEMA = {
    "measurements": {
        "Z", "A", "MT", "Projectile", "Reaction", "Element",
        "Energy", "dEnergy", "Data", "dData", "dData_assumed", "dData_adopted",
        "EXFOR_Entry", "EXFOR_Subentry", "Dataset_Number", "Year", "Author",
        "endf8", "endf8_chi_squared", "endf8_relative_error",
        "endf7-1", "endf7-1_chi_squared", "endf7-1_relative_error",
    },
    "subentries": {
        "Z", "A", "MT", "Reaction", "Element",
        "EXFOR_Entry", "EXFOR_Subentry", "E_min", "E_max",
    },
    "sentence_embeddings": {
        "EXFOR_Entry", "Sentence_Number", "Text", "Embedding",
    },
}

# The embedding contract. Both repos must agree on all three, or similarity search
# silently compares vectors from different spaces and returns plausible nonsense.
EMBEDDING_DIM = 768
EMBEDDING_DTYPE = np.float32
EMBEDDING_POOLING = "mean"  # mean-pooled over tokens, NOT the CLS token


class SchemaError(RuntimeError):
    """The database does not satisfy the contract this app is written against."""


def verify_schema(con, check_embeddings=True):
    """Raise SchemaError if the connected database is missing anything this app reads.

    Returns a list of non-fatal warnings (things that are odd but not disqualifying).
    """
    problems, warnings = [], []

    present = {r[0] for r in con.execute(
        "SELECT name FROM sqlite_master WHERE type='table'"
    )}

    for table, required in REQUIRED_SCHEMA.items():
        if table not in present:
            problems.append(f"missing table '{table}'")
            continue
        columns = {r[1] for r in con.execute(f"PRAGMA table_info({table})")}
        for column in sorted(required - columns):
            problems.append(f"table '{table}' is missing column '{column}'")

    if check_embeddings and "sentence_embeddings" in present:
        problems.extend(_verify_embeddings(con))

    # Two structurally identical embedding tables means the ML repo changed names
    # without cleaning up. Not fatal here (this app reads neither), but worth saying.
    if {"reports", "report_embeddings"} <= present:
        warnings.append(
            "both 'reports' and 'report_embeddings' exist; the data/ML repo should "
            "collapse these to one table so the KNN pipeline has a single source of truth"
        )

    if problems:
        raise SchemaError(
            "Database at this path does not match the schema NuGrade expects.\n  - "
            + "\n  - ".join(problems)
            + "\n\nThis database is generated by the data/ML repo. Regenerate it from a "
              "commit that matches this app, or update nugrade/db_contract.py if the "
              "schema change is intentional."
        )
    return warnings


def _verify_embeddings(con):
    """Check that stored embedding blobs have the expected dtype and dimensionality."""
    row = con.execute(
        "SELECT Embedding FROM sentence_embeddings WHERE Embedding IS NOT NULL LIMIT 1"
    ).fetchone()
    if row is None:
        return ["table 'sentence_embeddings' has no non-null embeddings"]

    vector = np.frombuffer(row[0], dtype=EMBEDDING_DTYPE)
    if vector.shape != (EMBEDDING_DIM,):
        return [
            f"embeddings are {vector.shape[0]}-dimensional under "
            f"{EMBEDDING_DTYPE.__name__}, expected {EMBEDDING_DIM}"
        ]
    return []
